### ISSUE TITLE
package.yml: Conflicts definieren

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cache_warmup#51]
```
conflicts:
    packages:
        media_manager: ">= 3"
        structure: ">= 3"
```

Siehe @gharlan s Vorschlag hier: https://github.com/FriendsOfREDAXO/cache_warmup/issues/50#issuecomment-278774852

**Comment by gharlan** [comment]
Wenn dann irgendwann https://github.com/redaxo/redaxo/issues/899 umgesetzt ist, kann man genauso dann auch nach unten Schranken setzen, wenn man mal mindestens eine Version brauchen sollte. 
Geht aktuell aber noch nicht. Also nach unten und oben beschränken, ohne eine feste Abhängigkeit zu haben.

Ich meine sowas:

```yaml
conflicts:
    packages:
        media_manager: "< 2.1 || >= 3"
```

Hieße dann: Wenn media_manager installiert ist, dann bitte >= 2.1 und < 3. Aber es muss nicht installiert sein.
